version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: clearway
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lehia2006
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:lehia2006@db:5432/clearway
      PORT: 3001
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend/clearway-ui
      args:
        VITE_URL_API: http://144.225.147.96:3001/api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: